auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 104857600   # 100MB
  grpc_server_max_send_msg_size: 104857600

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true  # 결과 캐시 활성화 여부
        max_size_mb: 100  # 결과 캐시 최대 크기 (MB 단위)

query_scheduler:
  max_outstanding_requests_per_tenant: 2048  # 테넌트 당 최대 대기 중인 요청 수

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  use_thanos_objstore: true
  object_store:
    storage_prefix: loki-prod
    s3:
      bucket_name: muzlive-loki-chunks
      endpoint: s3.ap-northeast-2.amazonaws.com
      region: ap-northeast-2
#      access_key_id: ${S3_ACCESS_KEY}
#      secret_access_key: ${S3_SECRET_KEY}
#  aws: # 자격 증명은 환경변수로 주는 걸 권장: AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
#    region: ap-northeast-2
#    endpoint: s3.ap-northeast-2.amazonaws.com
#    bucketnames: muzlive-loki-chunks     # 실제 S3 버킷 이름
#    s3forcepathstyle: false      # AWS S3는 보통 false (경우에 따라 true 필요 없음)
#    insecure: false              # TLS 사용
##  boltdb_shipper:                # 인덱스는 로컬 + S3 공유 저장
##    active_index_directory: /var/loki/index
##    cache_location: /var/loki/index-cache
#  tsdb_shipper:
#    active_index_directory: /tmp/loki/tsdb-index
#    cache_location: /tmp/loki/tsdb-cache
#    # (마이크로서비스로 index-gateway 쓸 때만)
#    # index_gateway_client:
#    #   server_address: dns:///index-gateway.<namespace>.svc.cluster.local:9095

ruler:
  storage:
    type: s3
    s3:
      bucketnames: muzlive-loki-chunks
      region: ap-northeast-2
#      endpoint: s3.ap-northeast-2.amazonaws.com
      s3forcepathstyle: true
      insecure: false

limits_config:
  retention_period: 744h  # 보존 기간: 데이터 보존 기간
  ingestion_rate_mb: 50
  ingestion_burst_size_mb: 100
  max_line_size: 6291456
  split_queries_by_interval: 0  # 쿼리 구간별 분할: 쿼리 결과를 어떤 간격으로 분할할 지 여부
  allow_structured_metadata: true # log 메타 데이터 허용 여부

compactor:
  working_directory: /tmp/loki/compactor  # 컴팩터 작업 디렉터리
  delete_request_store: s3  # 공유 저장소: Amazon S3
  compaction_interval: 10m  # 컴팩션 간격: 컴팩션 실행 간격
  retention_enabled: true  # 보존 활성화 여부
  retention_delete_delay: 2h  # 보존 삭제 지연: 삭제 전 대기 기간