apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki-ds
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: 'trace_id=(\w+)'
          url: '$${__value.raw}'
          datasourceUid: tempo-ds

  - name: Mimir
    type: prometheus
    uid: mimir-ds
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: true

  - name: Tempo
    type: tempo
    uid: tempo-ds
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki-ds
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false